/**
 * Themed banks of ORIGINAL Drake-style lines, tuned for runs/rides.
 *
 * Content policy (load-bearing, see CLAUDE.md):
 * - Every line is original writing. None are verbatim or near-verbatim Drake
 *   lyrics; each batch was screened against recognizable real lyrics before
 *   being added here.
 * - clean: fully safe for work. explicit: profanity allowed.
 * - Slurs are forbidden in BOTH tiers, always. Tests enforce this.
 */

export interface ThemeBank {
  /** Theme id, e.g. "comeUp". */
  key: string;
  /** Safe-for-work lines. */
  clean: readonly string[];
  /** Profanity-allowed lines, used only when explicit mode is enabled. */
  explicit: readonly string[];
}

export const THEME_BANKS: readonly ThemeBank[] = [
  {
    key: "comeUp",
    clean: [
      "started with nothing but the open road",
      "turned all that doubt into distance",
      "the come-up don't take days off",
      "every mile is another receipt",
      "grinding quiet while the city sleeps",
      "long way up, never looking down",
      "earned this one step at a time",
      "out here collecting splits, not excuses",
      "earned every split before the city woke up",
      "they slept in, I was negotiating with a hill",
      "nobody claps at mile two, run it anyway",
      "quiet laps now, loud results later",
      "the pavement knew me before anybody did",
      "dawn shift, no overtime, all gains",
      "came up off cold mornings and colder splits",
      "still punching the clock at sunrise pace",
      "small miles stack into something they can't ignore",
      "the grind don't post, it just logs miles",
      "every PR was a Tuesday nobody saw",
      "legs paid the rent on this confidence",
      "built the engine one boring mile at a time",
      "before the likes, it was just me and the road",
      "hill repeats are my version of a handshake deal",
      "sweat equity, compounding daily",
      "first one out, last one bragging",
      "out here cashing checks my training wrote",
      "the alarm hates me and I'm winning anyway",
      "miles in the bank before the banks open",
      "you call it a route, I call it a resume",
      "pace got better, circle got smaller",
      "rode past the doubt at kilometer one",
      "old me walked these hills, new me owns them",
      "dawn patrol, headlights still off",
      "long game legs, short term soreness",
      "the come-up smells like rain on asphalt",
      "splits whisper now, they'll shout in October",
      "no shortcuts on this loop, never were",
    ],
    explicit: [
      "ran my ass off while the group chat slept",
      "damn right the hill lost again",
      "legs screaming, ego saying hell no we don't stop",
      "fuck a snooze button, the road owed me money",
      "shit pace yesterday, vendetta pace today",
      "grinding so quiet they thought I quit, hell no",
      "woke up pissed and dropped a damn tempo about it",
      "earned this swagger one shitty headwind at a time",
      "hell of a climb when nobody believed the kid",
      "fuck the forecast, miles don't reschedule",
      "still that quiet motherfucker stacking miles at 5am",
      "no handouts, just hills and a bad fucking attitude",
    ],
  },
  {
    key: "loyalty",
    clean: [
      "loyal to the pace, loyal to the crew",
      "real ones already know the splits",
      "ran it solo but the day-ones felt it",
      "no new friends, just new personal bests",
      "kept the same heart, just a faster step",
      "same circle, faster splits, that's the whole story",
      "day ones at mile one, day ones at mile twenty",
      "the crew got smaller and the pace got colder",
      "running with the same five since the slow years",
      "loyalty is a long run, most can't hold the pace",
      "new shoes, old friends, same dawn pavement",
      "kept the circle tight and the cadence tighter",
      "my day ones know what mile zero looked like",
      "real ones show up for the 6am hill repeats",
      "we don't add to the group ride, we just get faster",
      "same roads, same brothers, better legs, okay",
      "everybody wants the finish, my crew loved the start",
      "the ones who paced me slow still pace me now",
      "small circle, long miles, no introductions needed",
      "trust is built on tempo runs nobody saw",
      "they joined at the peak, we climbed the whole hill",
      "drafting for my brothers since the slow days",
      "I count my real ones on one hand and one watch",
      "fair-weather friends miss the rain miles",
      "same crew at the trailhead every single dawn",
      "the pace improved, the guest list didn't",
      "loyal to the loop and the legs that ran it with me",
      "my circle small enough to fit in one paceline",
      "old friends hold your pace without asking",
      "we got faster together or not at all",
      "sweat with me in winter, celebrate in summer",
      "the day ones remember when a 5k felt far",
      "not taking applications, the paceline is full",
      "miles change you, the right people don't",
      "kept the same crew while the haters bought new bikes",
    ],
    explicit: [
      "ran the damn hills with the same four guys, again",
      "fuck a fair-weather pace partner, where's my crew",
      "my day ones don't flinch when the splits get ugly as hell",
      "shit got fast and nobody in my circle blinked",
      "loyalty is showing up at 5am, no excuses, no shit",
      "we suffered on these climbs together, that's the bond, damn",
      "hell of a tempo run with the only five I trust",
      "damn right we still ride together, ten years deep",
      "fuck the clout miles, I run for my people",
      "the circle stayed small and the legs got scary, shit",
      "real ones held my pace when it was embarrassing as hell",
    ],
  },
  {
    key: "theSix",
    clean: [
      "city lights sittin' in the rearview",
      "reppin' the 6 from the first stride",
      "took the long way home through the block",
      "skyline watching every lap I take",
      "cold night, warm heart, empty streets",
      "city lights blur when the splits get honest",
      "skyline watched me earn every quiet mile",
      "cold air and a heart rate only I understand",
      "midnight pavement keeps all my secrets",
      "the streetlights know my tempo by now",
      "dawn over the towers, legs already gone",
      "nobody out here but me and the skyline",
      "negative splits under neon, no witnesses",
      "the city sleeps, my legs negotiate",
      "5am and the streets finally tell the truth",
      "every bridge crossed before the city woke",
      "cold hands, warm legs, whole skyline to myself",
      "they post brunch, I post the sunrise loop",
      "downtown's empty and my pace knows it",
      "rode till the skyline turned to memory",
      "lonely at this pace, lovely at this hour",
      "the hill by the tower still owes me one",
      "miles before the meetings even exist",
      "stoplights green like they knew I was coming",
      "fog on the river, fire in the legs",
      "I count streetlamps instead of doubts",
      "the long way home looked too good tonight",
      "quiet flex: sub-forty before the sun",
      "skyline seats are free if your legs pay",
      "late nights gave me these splits",
      "breath fog and brake lights all the way down",
      "the overpass at 6am hits different",
      "city's coldest hour, my warmest pace",
      "running on streets that raised my patience",
      "the last climb before the lights come on",
    ],
    explicit: [
      "cold as hell out, splits still warm",
      "damn near floated past the skyline tonight",
      "legs said hell no, the skyline said go",
      "ran this whole damn city before sunrise",
      "fuck a snooze button, the skyline was up",
      "pace so cold the streetlights shivered, damn",
      "hell of a view when your legs do the work",
      "no traffic, no excuses, just me and the damn hills",
      "talked shit to the headwind the whole bridge",
      "the city tried me at mile nine, didn't fucking fold",
      "sweat froze, ego didn't, hell of a night",
    ],
  },
  {
    key: "flex",
    clean: [
      "feeling elevated, legs on cruise control",
      "heart rate high and the ego higher",
      "too locked in to feel the burn",
      "blessings landing on the pavement",
      "pace so clean it don't need a caption",
      "moving different since the last PR",
      "legs got a trophy case and it's getting crowded",
      "pace so cold the pavement asked for a jacket",
      "PR talk only, leave excuses at the trailhead",
      "dawn saw me first and it still couldn't keep up",
      "splits so clean they belong in a display case",
      "every hill on this route knows my name by now",
      "victory lap energy on a random Tuesday, yeah",
      "untouchable downhill, undeniable on the climb",
      "my watch ran out of compliments today",
      "moved into the leaderboard, brought furniture",
      "sweat equity paying dividends, check the splits",
      "quads holding press conferences after that one",
      "ran it like the city owed me rent, easy money",
      "negative splits, positive attitude, zero doubts",
      "the pavement keeps receipts and mine all say fast",
      "out here lapping yesterday's version of me",
      "crowned myself at mile six, nobody objected",
      "talk is cheap, my splits paid in full",
      "if the watch doesn't say record, it's broken",
      "woke up, broke the PR, stayed humble-ish",
      "legs like deadlines, always delivering early",
      "the hill blinked first",
      "this pace doesn't return calls to slower days",
      "mile one was a flex, mile ten was a statement",
      "dawn patrol champion, self-appointed, undefeated",
      "left a five-star review on that climb: too easy",
      "cadence steady, ego earned, calves carved",
      "broke the PR then waved at the sunrise, casual",
    ],
    explicit: [
      "splits so nasty the damn watch double-checked",
      "legs feel like hell, leaderboard says heaven",
      "PR'd so hard my shoes filed a damn complaint",
      "fast as hell and humble about none of it",
      "that hill talked shit so I had it for breakfast",
      "untouchable pace, check the fucking receipts",
      "took the long way home just to flex on the dawn, shit",
      "quads sore, ego fucking thriving",
      "said ten miles, lied like hell, ran twelve",
      "damn right that's my name on top of the segment",
      "sweat like a sinner, split like a goddamn prophet",
      "zero chill, full send, fuck a rest day",
    ],
  },
  {
    key: "feelings",
    clean: [
      "ran it out instead of texting back",
      "the pavement heard everything I didn't say",
      "five miles deep in a memory I should delete",
      "drafted the text, deleted it, ran the hill twice",
      "dawn miles for feelings I can't name yet",
      "left it all on the road, kept the rest to myself",
      "your street was on the route, I didn't slow down",
      "pace steady, heart somewhere else entirely",
      "the long way home because home got quiet",
      "splits even, everything else uneven",
      "outran the playlist, not the memory",
      "sweat is just the soft way of crying",
      "miles are cheaper than therapy, still pricey",
      "rode until the city looked like before",
      "every hill asked about you, I said nothing",
      "missed your call, caught the sunrise instead",
      "the legs remember what the heart forgets",
      "solo ride, two seats worth of silence",
      "ran past where we used to be us",
      "cadence high so the thoughts can't catch me",
      "told the dawn what I'd never text you",
      "old route, new me, same ache at mile six",
      "letting the headwind take what's left of it",
      "I count splits so I don't count regrets",
      "the road never asks why I'm out this late",
      "warmdown longer than it needed to be, like us",
      "kept the receipts in my legs, not my phone",
      "quiet miles for loud thoughts",
      "mile repeats and what-ifs, mostly what-ifs",
      "ran out of road before I ran out of feelings",
    ],
    explicit: [
      "damn near texted you at mile nine, kept running",
      "shit got heavy, so I ran until it wasn't",
      "fuck a rest day, my feelings needed the miles",
      "hell of a sunrise to be sad in front of",
      "deleted your number, the hill still hurt like shit",
      "missed you for six damn miles and called it tempo",
      "the headwind can have this shit, I'm done carrying it",
      "ran the long way so I wouldn't text dumb shit",
      "heart heavy as hell, splits light as ever",
      "fuck around and PR'd off pure heartache",
      "damn these quiet roads for letting me think",
      "still soft over it, still fast as hell though",
    ],
  },
  {
    key: "trustIssues",
    clean: [
      "doubters set alarms just to watch me lap them",
      "quiet miles speak louder than their group chat",
      "they watched the kudos and missed the work",
      "proof of pace for everyone who said slow down",
      "let the splits answer what I never will",
      "dawn run, receipts in negative splits",
      "they smiled at the start line, I noticed",
      "fake friends fade around mile four",
      "revenge is a tempo run nobody sees",
      "left the doubt at the bottom of the hill",
      "pavement keeps secrets better than they do",
      "my circle got smaller, my long run got longer",
      "they clocked my rest day, not my comeback",
      "silence plus six miles, that's the statement",
      "every hater is just cardio motivation now",
      "watched by many, paced by none",
      "the leaderboard remembers what they forgot",
      "doubt me quietly, I'll PR loudly",
      "legs don't gossip, they just deliver",
      "new pace, same people watching from the couch",
      "sweat is the only honest thing this week",
      "ran past the noise, kept the receipts",
      "trust the legs, question everybody else",
      "they wanted me tired, I came back tapered",
      "cold dawn, colder shoulder, fastest mile yet",
      "smile at the doubters, drop them on the climb",
      "proving them wrong one split at a time, yeah",
      "they bet against the comeback and lost again",
      "miles in the dark while they kept score",
    ],
    explicit: [
      "ran the doubt off, fuck a group chat opinion",
      "they said I fell off, so I dropped a damn PR",
      "fuck the forecast and the doubters, dawn miles",
      "hell of a split for somebody you slept on",
      "damn right I saw who unfollowed, kept running",
      "they wanted smoke, I gave them hill repeats",
      "talk shit, get lapped",
      "quiet revenge, loud-ass negative splits",
      "haters do their stalking, I do my damn tempo",
    ],
  },
];
